==== Overview

NOTE: The SSSD container is offered as a Tech Preview. All restrictions that apply to Tech Previews apply to the SSSD container.

The Red Hat Enterprise Linux Atomic SSSD Container Image provides the ipa-client and realmd tools for enrolling the host to an Identity Management (IdM) server or to connect it to an Active Directory domain. It makes it possible to run the System Security Services Daemon (SSSD) in a container to provide identity, authentication, and authorization services to the Atomic Host.

For more information about IdM, see the following guides:


* link:https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Linux_Domain_Identity_Authentication_and_Policy_Guide/index.html[Linux Domain Identity, Authentication, and Policy Guide] - This guide includes an introduction to IdM and the documentation for the ipa-client-install utility.

* link:https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Windows_Integration_Guide/index.html[Windows Integration Guide] - This guide includes documentation for realmd and SSSD in an Active Directory environment.

* link:https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/System-Level_Authentication_Guide/index.html[System-Level Authentication Guide] - This guide includes documentation for SSSD.

==== Basic SSSD container installation

. **Install the SSSD container.**
+
Run the following command on a Red Hat Enterprise Linux Atomic Host that has been registered with subscription-manager:
+
....
# atomic install rhel7/sssd [options]
....

. **Start the SSSD container that contains the SSSD daemon** :
+
....
# systemctl start sssd
....
+
This command runs a container. Note that the SSSD daemon is also installed on the host.

==== sssd container installation with ipa-client-install

. Confirm that IdM client is not configured on your system:
+
....
# atomic install rhel7/sssd
Using default tag: latest
4ad3c6991ef7: Download complete
bf63a676257a: Download complete
Status: Downloaded newer image for registry.access.stage.redhat.com/rhel7/sssd:latest
docker run --rm=true --privileged --net=host -v /:/host -e NAME=sssd -e IMAGE=rhel7/sssd -e HOST=/host rhel7/sssd /bin/install.sh
Initializing configuration context from host ...
One of password / principal / keytab is required.
Installation failed. Rolling back changes.
IPA client is not configured on this system.
....

. **atomic install** Run the following command, replacing **otp-password** with the password for your IdM server:
+
....
# atomic install rhel7/sssd --password otp-password
....
Note: "otp-password" in this command is the string generated by the **ipa host-add --random client.example.com** command.

. Start the sssd daemon:
+
....
# systemctl start sssd
....

==== Joining an sssd container to an Active Directory domain

**atomic install rhel7/sssd** calls **ipa-client-install** by default. This means that you must use **atomic install rhel7/sssd realm** to invoke **realmd**.

. **realm join** does not accept passwords as command-line parameters. Pass the password with the following command:
+
....
# echo $PASSWORD > /etc/sssd/realm-join-password
....

. Run **atomic install rhel7/sssd realm join** and specify the realm that you intend to join:
+
....
# atomic install rhel7/sssd realm join ADREALM12.COM
docker run --rm=true --privileged --net=host -v /:/host -e NAME=sssd -e IMAGE=rhel7/sssd -e HOST=/host rhel7/sssd /bin/install.sh realm join ADREALM12.COM
Initializing configuration context from host ...
Password for Administrator:
Copying new configuration to host ...
Service sssd.service configured to run SSSD container.
....

. Start the sssd daemon:
+
....
# systemctl start sssd
....

. Confirm that SSSD resolves identities from the Active Directory domain:
+
....
# id Administrator@ADREALM12.COM
uid=1397800500(administrator@ADREALM12.COM) gid=1397800513(domain users@ADREALM12.COM
....

==== Further information on SSSD

The link:https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Windows_Integration_Guide/SSSD-AD.html#sssd-identity[RHEL 7 Windows Integration Guide] describes the function of SSSD and the configuration of SSSD with Active Directory.
