CSG
===


Container Security Guide
------------------------


Zac Dover

Customer Content Services
Brisbane
<zdover@redhat.com>

Copyright © 2015 | Zac Dover, CCS, Red Hat| This material may only be
distributed subject to the terms and conditions set forth in the GNU Free
Documentation License (GFDL), V1.2 or later (the latest version is
presently available at http://www.gnu.org/licenses/fdl.txt).

Abstract

How to secure Docker Containers

------------------------------------------------------------------------



Chapter 1. Buidling and Distributing Containers
===============================================

This chapter describes security concerns involving the building and
distribution of Docker conatiners.


1.1. Docker's Unsigned Binary
-----------------------------

Docker's official binary installation is not signed. We hope that this
will change by the time this document goes to press, but if it doesn't,
we're going to say it again: Docker's official binary installation is not
signed.


1.2. The Dangers of Untrusted Content
-------------------------------------

The process of using RPMs involves separation between the retrieval phase
of installation and the actual installation phase of installation. This
separation between retrieval and installation does not exist in the
Docker workflow. There are a number of CVEs related to this issue (FIXME:
provide this list). Docker images are stored as tars (mostly), and they
can escape the docker daemon without your knowing it.

docker pull is an active process - unlike RPMs, there is no separation

docker containers run as root - you should only run Docker content that
has originated from trusted vendors (that includes Red Hat, and in fact
is primarily Red Hat).

no one else is curating containers (asis/whereis) -
http://www.banyanops.com/blog/analyzing-docker-hub/ - Containers are
uploaded into Docker Hub, and no maintenance is done in the Docker Hub
after they're uploaded there. This means that you're at the mercy of the
diligence and intelligence of the people who created the images you're
inviting into your Docker daemon host.


1.3. Keeping Containers Fresh and Updateable
--------------------------------------------

This section describes processes and practices that ensure that your
containers are fresh and updateable.


1.3.1. Never Pull Naked in FROM Instructions

Always list the registry from which you're pulling in the FROM commands
you use. In Red Hat's case, that means that you have to include the whole
name of the Red Hat Docker registry.

FIXME: Example code here


1.3.2. Use yum update Tools

Always run yum update && yum clean all or an equivalent to ensure that
you're getting the most-updated base image possible. These commands
update the RPM content associated with the base image. This reduces the
exposed attack surface.


1.3.3. Using Docker Caching to Your Advantage

This section explains how to use Docker caching to make your Dockerfiles
more efficient for your workflow.

1.3.3.1. Order Instructions to Take Advantage of Caching

Docker assumes that each instruction is deterministic. Docker assumes
that these instructions are not associative. If it encounters the same
instructions in the same order, it caches the results. This means that if
you have the instruction FROM foo: dnf -y update in the same two
Dockerfiles in the same order, Docker will create the same base image
from that point.

Always perform installations in Dockerfiles in the same order to take
advantage of Docker caching. Break tasks into thematic components (for
example "adding users" or "updating software") in order to take best
advantage of Docker's caching utlitities. Red Hat recommends that your
company create a Dockerfile style guide, if you have the time and
resources.

1.3.3.2. Deliberately Breaking Caching

There may be times when you want to subvert Docker's default caching
behavior. This section explains what to do when that's what you want to
do.

Here's the scenario: You are aware of an update, but it's not covered by
the update in the Dockerfile because Docker wrongly assumes that "yum
update" returns the same state. On a given day, though, that doesn't
happen because "yum update" isn't a deterministic command. The three
methods for forcing this are: (1) if it's a single machine, you can
delete and recereate the image, (2) you can insert a nonce command like
"echo uniquething", which intentionally breaks the caching, and (3) you
can use a buildsystem like the OpenShift buildsystem, which is aware of
this issue and permits you to demand a fresh images from OSBS (OpenShift
BuildSystem).

1.3.3.3. Deleting and Recreating Images

To Be Done.

1.3.3.4. Using 'echo someuuid'

To Be Done.


1.4. Creating Containers with OSBS/Atomic Reactor
-------------------------------------------------

To Be Done. zdover and tjay expect this information to land the week of
16 Aug 2015.


1.5. Ensuring the Provenance of Containers
------------------------------------------

The easiest thing to do to ensure the provenance of your containers is to
run a private registry yourself. Both OpenShift and Satellite are Red Hat
products that have built-in image service options. The recommendation is
that your images should not contain any sensitive information. If anyone
overhears them, it won't be a problem. This means that you should always
use TLS (transport layer security), but you don't need to use
authentication. Things that need to remain confidential should be
abstracted up a level to the orchestration level, which we will discuss
in the Kubernetes and OpenShift sections of this document.


1.5.1. Running a Private Registry with Satellite

This section explains how to run a private registry with Satellite in
order to secure the provenance of your Docker images. To Be Done.

1.5.1.1. Running a Private Registry

This section explains how to run a private registry in order to secure
the provenance of your Docker images. To Be Done.

1.5.1.2. Distributing Docker Images Without a Registry

what is the best way to distribute Docker images without a registry? You
can distribute docker images as tarballs that are created with the
"docker save" command and loaded with the "docker load" command. You can
secure their provenance using signed-hash methods, the same way that you
secure other things.

http://fedora.uberglobalmirror.com/fedora/linux//releases/21/Docker/x86_64/
- fedora, for instance, has a hash file and a tarball associated with
that hash file, as you can see in the link here.

1.5.1.3. Distributing Docker Images Without a Registry

To Be Done. Define Notary. https://github.com/docker/notary

notary is a TBD as of 04 Aug 2015 but we're going to push to get it more
developed as of the first week of August (zdover, writing on the word of
tjay)


1.6. Leveraging Kubernetes and OpenShift to Ensure that Containers are
Immutable
----------------------------------------------------------------------

Why is immutability good for security? It decreases the damage that can
be done with a local compromise. The images themselves don't have any
secrets and they don't save any state that could get corrupted, and
they're trivial to verify because they never change.

("immutable" means, in this context "a container that has no state")


1.6.1. Ways to Leverage Kubernetes and OpenShift

This section describes ways to leverage Kubernetes and OpenShift to
create immutable (stateless) container images.

  1. 

    Using Volume Mounting

    bringing in external data that is mutable (for instance, WordPress
    content or a database)

  2. 

    Using Services

    Kubernetes and OpenShift have matchmaking services. A container can
    be designed to depend generically on a database, and the details of
    logging into that database can be provided at runtime.

  3. 

    Using Templating

    This is the above idea, but applied to buildtime. If containers need
    to have users with a certain UID to run on a certain cluster,
    Dockerfiles don't provide a way of doing that. You can use plugins to
    the OpenShift buildsystem to customize a given build if this is the
    kind of thing you need.

  4. 

    Using Github Repositories

    Use docker pull to pull in live content at runtime, for example at a
    private or public git repository. OpenShift has features that take
    this to another level: they allow you to ignore all the container
    details and have an application all of whose details are hosted in a
    github repo.


1.7. Leveraging Kubernetes to Ensure that Containers Do Not Store Secrets
or Sensitive Information
-------------------------------------------------------------------------

Kubernetes has a "secrets" functionality that allows memory-hosted
secrets to be inserted as virtual files at runtime. This should be used
for all confidential information such as authentication details and
encryption keys (we will have examples of this here).


1.7.1. Using Secrets

TBD. Include examples. 16 Aug 2015, zdover.


1.8. Container Analysis Tools
-----------------------------

This section describes tools for the analysis of containers.


1.8.1. OpenShift Tool Similar To OpenSCAP

OpenShift should have a tool similar to openSCAP that is unnamed of of 04
Aug 2015.


1.8.2. Atomic Command

if you use the "atomic" command, you'll know which layers went into your
images, and if any of those layers have been updated, you will know that
you should rebuild your image. INSERT EXAMPLE HERE.

Checking if underlying layers need to be updated.


1.8.3. Things To Add to this Part

  1. 

    Canonical Dockerfile - this needs to be called something other than
    "Canonical", since there is a company called "Canonical" and this
    term will be ambiguous in the minds of some of our readers if it
    stands.

  2. 

    Example of breaking caching - What is breaking caching? Why would you
    want to break caching? Why would you want to make sure that you don't
    break caching?

  3. 

    Example of a OSBS/reactor interaction

  4. 

    Canonical pod example showing secrets volume mounting and github deps
    - Again, we need to choose a word that isn't "canonical" so that
    ignorant readers don't think that we're talking about Ubuntu.

  5. 

    Showing how to be Atomic compatible throughout



Appendix A. Revision History
============================

Revision History

Revision 0.0-0

Sun Aug 16 2015

Enter your first name here. Enter your surname here.

Initial creation by publican



Index
=====
